var CONSTRUCTION_DATA = {
  agency: {
    name: 'Reozix Construction',
    location: 'Brisbane, QLD',
    phone: '+61 7 3186 2400',
    email: 'build@reozix.com.au',
    licence: '15123456'
  },
  projects: [
    {
      id: 'proj-001',
      title: 'Meridian Tower Executive Office Fit-Out',
      type: 'Commercial Fit-Out',
      suburb: 'Brisbane CBD',
      budget: 1450000,
      duration: '14 weeks',
      sqm: 1350,
      description: 'Full-floor fit-out of an executive suite across Level 12 of the Meridian Tower, including an open-plan workspace for 120 staff, meeting rooms and a client boardroom. Delivered a data-centre-rated ICT suite, commercial kitchen and end-of-trip facilities without a single day of business interruption.',
      testimonial: { quote: 'Reozix took a bare floor and delivered a workspace our whole team is proud of. They ran the fit-out around our trading hours and handed over a week ahead of schedule.', client: 'David Ashworth', role: 'Managing Director' },
      photos: 8,
      features: ['Open-plan workspace', 'Executive boardroom', 'End-of-trip facilities', 'Commercial kitchen', 'Data-centre ICT suite'],
      completed: '2026-03',
      status: 'completed'
    },
    {
      id: 'proj-002',
      title: 'The Foundry Retail Flagship Store',
      type: 'Commercial Fit-Out',
      suburb: 'Fortitude Valley',
      budget: 620000,
      duration: '10 weeks',
      sqm: 420,
      description: 'Boutique flagship fit-out for an Australian menswear label in the heart of the Valley\'s retail precinct. Exposed-brick feature walls, brushed-steel fixtures and a sculptural central display island, all delivered to a strict opening-date deadline ahead of the summer season.',
      testimonial: { quote: 'Our new flagship opened on time and on budget for the Christmas rush. The fit-out has lifted our brand well beyond anything we had in the old store.', client: 'Marcus Hendry', role: 'Brand Director' },
      photos: 6,
      features: ['Exposed-brick feature walls', 'Custom steel fixtures', 'Display joinery', 'Designer lighting', 'Café kiosk'],
      completed: '2025-11',
      status: 'completed'
    },
    {
      id: 'proj-003',
      title: 'Wickham Street Medical Centre Fit-Out',
      type: 'Commercial Fit-Out',
      suburb: 'Fortitude Valley',
      budget: 1100000,
      duration: '16 weeks',
      sqm: 780,
      description: 'Ground-floor medical centre fit-out with eight consult rooms, a treatment suite and pathology collection room, built to Class B healthcare compliance. Sound-rated partitions, lead-lined imaging walls and full accessibility upgrades throughout.',
      testimonial: { quote: 'From the first site walk to handover, Reozix managed the healthcare compliance requirements without drama. Our patients comment on the calming fit-out every day.', client: 'Dr Priya Raghavan', role: 'Practice Principal' },
      photos: 7,
      features: ['Class B healthcare fit-out', 'Eight consult rooms', 'Treatment suite', 'Lead-lined imaging walls', 'Accessibility upgrades'],
      completed: '2025-08',
      status: 'completed'
    },
    {
      id: 'proj-004',
      title: 'Milton Creative Agency Refurbishment',
      type: 'Commercial Fit-Out',
      suburb: 'Milton',
      budget: 480000,
      duration: '8 weeks',
      sqm: 560,
      description: 'Refresh of a two-level creative agency in a converted Milton warehouse, with a new mezzanine, breakout zones and an open studio floor. Existing heritage timber trusses retained and highlighted with acoustic baffle ceilings.',
      testimonial: { quote: 'The team has kept our studio live throughout the refurb. They\'re working around our deadlines and the new mezzanine is already taking shape.', client: 'Catherine Lowe', role: 'Creative Director' },
      photos: 5,
      features: ['Heritage trusses retained', 'New mezzanine level', 'Acoustic baffle ceilings', 'Breakout zones', 'Studio floor'],
      completed: '2026-10',
      status: 'in-progress'
    },
    {
      id: 'proj-005',
      title: 'Latitude Street Second Storey Addition',
      type: 'Residential Extension',
      suburb: 'Paddington',
      budget: 385000,
      duration: '18 weeks',
      sqm: 95,
      description: 'Second-storey addition over an existing worker\'s cottage in Paddington, adding two bedrooms, a study and a parent\'s retreat. Engineered lightweight frame, new stair access and a window-wall capturing views back over the suburb\'s rooftops.',
      testimonial: { quote: 'We stayed in the cottage throughout and barely noticed the build. The new upstairs level has completely transformed how we live in the house.', client: 'Sarah & Tom Whitfield', role: 'Homeowners' },
      photos: 7,
      features: ['Second storey addition', 'Master retreat', 'New staircase', 'Rooftop outlook', 'Lightweight framing'],
      completed: '2026-01',
      status: 'completed'
    },
    {
      id: 'proj-006',
      title: 'Coorparoo Entertainer\'s Deck & Patio',
      type: 'Residential Extension',
      suburb: 'Coorparoo',
      budget: 88000,
      duration: '6 weeks',
      sqm: 42,
      description: 'Timber-framed deck and covered patio extension off the rear of a Coorparoo family home, with an outdoor kitchen prep area and built-in bench seating. Clear-span roof, LED strip lighting and a low-maintenance composite decking surface.',
      testimonial: { quote: 'The deck is the best room in the house now. Six weeks, minimal mess, and the kids practically live out there.', client: 'Nathan Boyd', role: 'Homeowner' },
      photos: 5,
      features: ['Timber-framed deck', 'Covered patio roof', 'Outdoor kitchen prep', 'Built-in seating', 'Composite decking'],
      completed: '2025-10',
      status: 'completed'
    },
    {
      id: 'proj-007',
      title: 'Ashgrove Queenslander Rear Extension',
      type: 'Residential Extension',
      suburb: 'Ashgrove',
      budget: 240000,
      duration: '12 weeks',
      sqm: 68,
      description: 'Single-level rear extension to a classic Ashgrove Queenslander, opening the kitchen, dining and living into one light-filled space. VJ-lined walls, recycled hardwood floorboards and a new verandah that frames the established garden.',
      testimonial: { quote: 'Reozix matched the new work to our 1920s Queenslander beautifully. The extension feels like it has always been there.', client: 'Helena Marsh', role: 'Homeowner' },
      photos: 6,
      features: ['VJ-lined walls', 'Recycled hardwood floors', 'Open-plan kitchen/dining', 'New verandah', 'Period-matched detailing'],
      completed: '2025-12',
      status: 'completed'
    },
    {
      id: 'proj-008',
      title: 'Paddington Kitchen & Living Extension',
      type: 'Residential Extension',
      suburb: 'Paddington',
      budget: 320000,
      duration: '14 weeks',
      sqm: 75,
      description: 'Ground-floor kitchen, dining and living extension to a terraced Paddington home on a steep block. Full-height glazing to the rear, a raked ceiling and an engineered retaining wall that created usable outdoor space from a once-unusable slope.',
      testimonial: { quote: 'The full-height glass wall is in and the raked ceiling has transformed the space. Reozix\'s weekly updates keep us confident through every stage.', client: 'James O\'Connor', role: 'Homeowner' },
      photos: 6,
      features: ['Full-height glazing', 'Raked ceiling', 'Engineered retaining wall', 'Custom joinery', 'In-floor heating'],
      completed: '2026-11',
      status: 'in-progress'
    },
    {
      id: 'proj-009',
      title: 'New Farm Contemporary Custom Home',
      type: 'New Build',
      suburb: 'New Farm',
      budget: 2400000,
      duration: '34 weeks',
      sqm: 420,
      description: 'Four-bedroom custom residence on a corner allotment in New Farm, with a double-height entry, pool and basement carpark for three cars. Cantilevered upper level, full-height glazing and a mineral-finished swimming pool wrapped by a landscaped garden.',
      testimonial: { quote: 'Our vision was ambitious — a floating upper floor over a pool in the middle of New Farm. Reozix engineered and built it flawlessly.', client: 'Anthony & Renee Callis', role: 'Homeowners' },
      photos: 9,
      features: ['Double-height entry', 'Cantilevered upper level', 'Basement carpark', 'Mineral-finished pool', 'Landscaped garden'],
      completed: '2026-02',
      status: 'completed'
    },
    {
      id: 'proj-010',
      title: 'Hamilton Dual-Living Duplex',
      type: 'New Build',
      suburb: 'Hamilton',
      budget: 1800000,
      duration: '30 weeks',
      sqm: 510,
      description: 'Two-titling duplex development in Hamilton with mirrored floor plans, double garages and private courtyards to each residence. Feature-brick exteriors, high ceilings and a shared landscaped entry with secure video intercom.',
      testimonial: { quote: 'The duplexes were rented within a fortnight of completion. Reozix managed the whole build and the finishes are well above market standard.', client: 'Rebecca Tran', role: 'Property Developer' },
      photos: 8,
      features: ['Two-titling duplex', 'Double garages', 'Private courtyards', 'Feature-brick exteriors', 'High ceilings'],
      completed: '2025-09',
      status: 'completed'
    },
    {
      id: 'proj-011',
      title: 'Chelmer Riverfront Residence',
      type: 'New Build',
      suburb: 'Chelmer',
      budget: 2800000,
      duration: '40 weeks',
      sqm: 480,
      description: 'Riverfront home on the Brisbane River at Chelmer with five bedrooms, a rooftop terrace and a private pontoon. Reinforced flood-resistant ground floor, full-height glazing to the water and a four-car basement garage.',
      testimonial: { quote: 'Flood-resilient construction was non-negotiable for us and Reozix delivered above code. The rooftop terrace alone was worth the build.', client: 'Greg Maller', role: 'Company Director' },
      photos: 9,
      features: ['Riverfront aspect', 'Rooftop terrace', 'Private pontoon', 'Flood-resistant construction', 'Four-car basement'],
      completed: '2025-06',
      status: 'completed'
    },
    {
      id: 'proj-012',
      title: 'Hamilton Townhouse Development',
      type: 'New Build',
      suburb: 'Hamilton',
      budget: 2100000,
      duration: '36 weeks',
      sqm: 690,
      description: 'Three-attached-townhouse development near the Hamilton racecourse, each with three bedrooms, a rooftop courtyard and a single garage. Rendered-and-battens exterior, landscaped common areas and a shared driveway with intercom entry.',
      testimonial: { quote: 'Two of the three townhouses sold off the plan. The build quality earned us a premium over our own conservative estimates.', client: 'Melissa Fielding', role: 'Director, Fielding Property' },
      photos: 8,
      features: ['Three townhouses', 'Rooftop courtyards', 'Rendered & battens exterior', 'Intercom entry', 'Landscaped common areas'],
      completed: '2026-04',
      status: 'completed'
    },
    {
      id: 'proj-013',
      title: 'Chelmer Family Home on Large Lot',
      type: 'New Build',
      suburb: 'Chelmer',
      budget: 950000,
      duration: '24 weeks',
      sqm: 280,
      description: 'Four-bedroom family home on a level 600sqm block in Chelmer, with an open-plan living core, a separate media room and a covered alfresco. Linerboard ceilings, wide-board oak flooring and a ducted zoned air-conditioning system.',
      testimonial: { quote: 'Reozix built our home while we were interstate and kept us updated every week with photos. Move-in was seamless.', client: 'Peter & Fiona Lawson', role: 'Homeowners' },
      photos: 7,
      features: ['Four bedrooms', 'Covered alfresco', 'Separate media room', 'Wide-board oak flooring', 'Zoned air conditioning'],
      completed: '2026-06',
      status: 'completed'
    },
    {
      id: 'proj-014',
      title: 'Bulimba Queenslander Whole-Home Renovation',
      type: 'Renovation',
      suburb: 'Bulimba',
      budget: 580000,
      duration: '20 weeks',
      sqm: 250,
      description: 'Top-to-bottom renovation of a character Queenslander in Bulimba, including a re-plumbed and re-wired ground floor, new kitchen and bathrooms, and the reinstatement of the original chamferboards and fretwork. Heritage-compatible materials throughout.',
      testimonial: { quote: 'Reozix respected the bones of our Queenslander while delivering a genuinely modern home. The heritage restoration work is outstanding.', client: 'Fiona Healy', role: 'Homeowner' },
      photos: 8,
      features: ['Heritage restoration', 'New kitchen & bathrooms', 'Re-wire & re-plumb', 'Chamferboard reinstatement', 'Fretwork detailing'],
      completed: '2025-07',
      status: 'completed'
    },
    {
      id: 'proj-015',
      title: 'Newstead Kitchen & Bathroom Renovation',
      type: 'Renovation',
      suburb: 'Newstead',
      budget: 140000,
      duration: '7 weeks',
      sqm: 65,
      description: 'Complete renovation of a dated kitchen and main bathroom in a Newstead apartment, with stone benchtops, soft-close cabinetry and a walk-in rain shower. All services relocated within the existing footprint to avoid structural changes.',
      testimonial: { quote: 'Seven weeks, on budget, and the kitchen is now the heart of the apartment. The trades were respectful and tidy throughout.', client: 'Alan Pierce', role: 'Apartment Owner' },
      photos: 6,
      features: ['Stone benchtops', 'Soft-close cabinetry', 'Walk-in rain shower', 'Feature tile splashback', 'Relocated services'],
      completed: '2026-05',
      status: 'completed'
    },
    {
      id: 'proj-016',
      title: 'West End Heritage Terrace Restoration',
      type: 'Renovation',
      suburb: 'West End',
      budget: 420000,
      duration: '26 weeks',
      sqm: 180,
      description: 'Sympathetic restoration of an 1890s West End terrace, including structural repairs, reinstatement of the cast-iron lacework and an updated kitchen and bathrooms in period-appropriate style. Worked under council heritage approvals with a specialist heritage consultant.',
      testimonial: { quote: 'Navigating the heritage approvals was daunting, but Reozix handled every submission and kept the character intact. The lacework looks like the day it was cast.', client: 'Victor Chen', role: 'Homeowner' },
      photos: 7,
      features: ['Cast-iron lacework', 'Structural repairs', 'Period-appropriate kitchen', 'Heritage approvals', 'Specialist restoration'],
      completed: '2025-11',
      status: 'completed'
    },
    {
      id: 'proj-017',
      title: 'Bulimba Modern Kitchen Renovation',
      type: 'Renovation',
      suburb: 'Bulimba',
      budget: 95000,
      duration: '5 weeks',
      sqm: 40,
      description: 'Stripped and rebuilt the kitchen of a Bulimba family home with a two-pack cabinetry scheme, waterfall stone island and integrated appliances. Floorplan opened to the adjoining meals area with a full-width servery window.',
      testimonial: { quote: 'The waterfall island is the showpiece and Reozix delivered it exactly to the render. Cooking is a joy now.', client: 'Kylie Anderton', role: 'Homeowner' },
      photos: 5,
      features: ['Waterfall stone island', 'Two-pack cabinetry', 'Integrated appliances', 'Servery window', 'Under-bench lighting'],
      completed: '2026-02',
      status: 'completed'
    },
    {
      id: 'proj-018',
      title: 'West End Bathroom & Laundry Renovation',
      type: 'Renovation',
      suburb: 'West End',
      budget: 120000,
      duration: '6 weeks',
      sqm: 35,
      description: 'Renovation of a three-piece bathroom and adjacent laundry in a West End apartment, with large-format porcelain tiles, a freestanding bath and a combined laundry utility wall. Waterproofing and re-plumbing completed to current codes.',
      testimonial: { quote: 'We\'ve been kept in the loop at every stage — weekly updates and photos. Halfway through and the standard of work is exactly what we hoped for.', client: 'Megan Delaney', role: 'Apartment Owner' },
      photos: 5,
      features: ['Large-format porcelain tiles', 'Freestanding bath', 'Combined laundry wall', 'Re-waterproofing', 'Re-plumbing'],
      completed: '2026-09',
      status: 'in-progress'
    }
  ],
  services: [
    {
      id: 'svc-001',
      title: 'Commercial Fit-Outs',
      icon: '🏢',
      description: 'Turnkey fit-outs for offices, retail and medical spaces across Brisbane\'s CBD and inner suburbs. We take your space from bare shell to move-in ready — planning, approvals, construction and handover all under one contract.',
      process: ['Initial consultation', 'Design & documentation', 'Construction & fit-out', 'Handover & aftercare'],
      timeline: '8–16 weeks',
      priceRange: '$250K–$2M',
      includes: ['Demolition & strip-out', 'Full design & construction', 'Commercial-grade finishes', 'End-of-trip & amenities', 'Move-in ready handover', 'Defects liability period'],
      projects: ['proj-001', 'proj-002', 'proj-003']
    },
    {
      id: 'svc-002',
      title: 'Residential Extensions',
      icon: '🏠',
      description: 'Second-storey additions, rear extensions and deck builds that give your Brisbane home the space it needs — without the cost of moving. We handle council approvals and engineer every addition to the existing structure.',
      process: ['Site consultation & feasibility', 'Design & council approvals', 'Construction', 'Handover & finishing'],
      timeline: '10–20 weeks',
      priceRange: '$80K–$400K',
      includes: ['Council approval assistance', 'Structural engineering', 'Full construction', 'Flooring & finishes', 'Painting & joinery', 'Garden reinstatement'],
      projects: ['proj-005', 'proj-007', 'proj-008']
    },
    {
      id: 'svc-003',
      title: 'New Builds',
      icon: '🏗️',
      description: 'Custom homes, duplexes and townhouse developments built to your plans or designed from the ground up. Fixed-price contracts, a dedicated site supervisor and a 10-year structural warranty on every build.',
      process: ['Design consultation', 'Council & approvals', 'Construction', 'Handover & warranty'],
      timeline: '6–10 months',
      priceRange: '$400K–$3M',
      includes: ['Custom architectural design', 'Fixed-price contract', 'Dedicated site supervisor', 'Premium materials', '10-year structural warranty', 'Landscaping'],
      projects: ['proj-009', 'proj-010', 'proj-011']
    },
    {
      id: 'svc-004',
      title: 'Renovations',
      icon: '🔨',
      description: 'Kitchens, bathrooms and whole-home renovations that modernise your space without losing its character. From heritage restorations to contemporary makeovers, our licensed trades deliver clean, on-time transformations.',
      process: ['Consultation & scope', 'Design & approvals', 'Construction', 'Handover & final clean'],
      timeline: '4–10 weeks',
      priceRange: '$80K–$600K',
      includes: ['Detailed scope & fixed quote', 'Design & approvals', 'Licensed trades', 'Kitchen & bathroom specialists', 'Finish & detail work', 'Final clean'],
      projects: ['proj-014', 'proj-015', 'proj-016']
    }
  ],
  credentials: {
    licence: {
      number: '15123456',
      title: 'QBCC Builder Licence',
      class: 'Open — Unlimited'
    },
    insurance: [
      { type: 'Public Liability', cover: '$20M' },
      { type: 'Home Warranty', cover: 'Per QBCC scheme' },
      { type: 'Contract Works', cover: 'Full project value' }
    ],
    memberships: [
      { name: 'Master Builders Queensland', since: '2014' },
      { name: 'Housing Industry Association', since: '2016' },
      { name: 'Australian Institute of Building', since: '2018' }
    ],
    safety: {
      scheme: 'WorkCover Queensland',
      record: 'No lost-time injuries in the past 24 months',
      inductions: 'All site personnel inducted and White Card certified'
    },
    stats: {
      projectsCompleted: 140,
      yearsOperating: 12,
      teamSize: 45,
      repeatClients: '68%',
      sqmBuilt: 52000
    }
  }
};
